//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Untt_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guests
    {
        public int Id { get; set; }
        public string fio { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string flag { get; set; }
    }
}
